---

- name: Running apt-get update
  apt: update_cache=yes

- name: Running apt-get upgrade
  apt: upgrade=dist 

- name: Installing Samba dependecies
  apt: 
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ packages_ubuntu }}"

- name: Copy smb.conf
  template: 
    src: etc_samba_smb.conf.j2
    dest: /etc/samba/smb.conf
    backup: yes
  notify:
    - Restart Samba 

- name: Create Samba users group
  group:
    name: "{{ samba_group_name }}"
    state: present

- name: Add the Users to Samba group
  user:
    name: "{{ item.name }}" 
    groups: "{{ samba_group_name }}" 
    append: yes
  with_items: "{{ samba_users }}"

#- name: Create Samba Password for User(s)
#  shell: "(echo {{ item.smbpasswd }}; echo {{ item.smbpasswd }}) | smbpasswd -s -a {{ item.name }}"
#  with_items: "{{ samba_users }}"

- name: "Check that {{ public_share_path }} exist"
  stat:
    path: "{{ public_share_path }}"
  register: public_dir_exists

- name: "Create {{ public_share_path }} directory"
  file:
    state: directory
    path: "{{ public_share_path }}"
    owner: nobody
    group: nogroup
    mode: 0755
    recurse: yes
  when: public_dir_exists.stat.exists == False

- name: "Check that {{ private_share_path }} exist"
  stat:
    path: "{{ private_share_path }}"
  register: private_dir_exists

- name: "Create {{ private_share_path }} directory"
  file:
    state: directory
    path: "{{ private_share_path }}"
    owner: root 
    group: "{{ samba_group_name }}"
    mode: 1770
  when: private_dir_exists.stat.exists == False

## Dodanie plików do udziałów samby
